- name: install percona-release
  apt:
    deb: https://repo.percona.com/apt/percona-release_latest.generic_all.deb
- name: setup pt
  command: percona-release enable pt
- name: install percona-toolkit
  apt:
    name: percona-toolkit
    update_cache: true
